name: ci
on:
  push:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 30
    runs-on: macos-14
    name: Test
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1-beta'
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: maiyama18/SnapshotTestingSampleAppSnapshots
          path: SnapshotTestingSampleAppSnapshots
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Copy Snapshots
        run: |
          mkdir -p SampleAppSnapshotTests/__Snapshots__
          cp -r SnapshotTestingSampleAppSnapshots/* SampleAppSnapshotTests/__Snapshots__/
      - name: Debug
        run: |
          ls SampleAppSnapshotTests/*
      - name: Test
        run: |
          xcodebuild -scheme SampleApp -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15,OS=18.1" test